.\" This is an -*- nroff -*- source file.
.TH DIA 1X "3 July 1999"
.SH NAME
Dia \- a diagram drawing program
.SH SYNOPSIS
.B dia
[\-h] [\-\-help] [\-e \fIOUTPUT\fP] [\-\-export\-to\-ps=\fIOUTPUT\fP] [ files ... ]
.SH DESCRIPTION
.PP
\fIDia\fP is used to create diagrams. Dia has a number of basic tools,
like lines and boxes but can also dynamically load "sheets". A sheet
is a collection of tools that are used in a certain type of diagram.
.PP
Most diagram objects in \fIDia\fP has "handles". Lines can be
connected to these handles and this way graph structures can be
formed. When objects are moved or resized the connections will follow
the objects.
.PP
Diagrams drawn in \fIDia\fP can be exported PostScript.
.SH OPTIONS
\fIDia\fP accepts the following options:
.TP 8
.B  \-h, \-\-help
Display a list of all commandline options.
.TP 8
.B  \-e OUTPUT, \-\-export\-to\-ps=OUTPUT
Export the first file given to OUTPUT.
.
.SH SEE ALSO
.BR X (1)
.SH COPYRIGHT
Copyright \(co 1999 Alexander Larsson

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation. 
.
.SH AUTHORS
Alexander Larsson <alla@lysator.liu.se>

This manual was written by Fredrik Hallenberg <hallon@lysator.liu.se>
