#!/bin/sh

str=core-translation-report
cat <<__EOF__ >$str
*** PO/core/gettext translation report: ***
(Absence of a language code means 0% translation for that language)
(Help for translations (and/or much more) is of course welcome !)

(Please note that 100% doesn't mean that the work is complete: have you 
 checked the sheet translations for your language too ?)
__EOF__
./po-checktrans.py $* >>$str || cat <<__EOF__ >>$str
E: po-checktrans failed to run. Please check that python is installed
E: on your system. 
__EOF__

cat $str
exit 0
