/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_sheets_main_dialog (void);
GtkWidget* create_sheets_new_dialog (void);
GtkWidget* create_sheets_edit_dialog (void);
GtkWidget* create_sheets_remove_dialog (void);
GtkWidget* create_sheets_shapeselection_dialog (void);
