/* Dia -- a diagram creation/manipulation program -*- c -*-
 * Copyright (C) 2002 Alexander Larsson
 *
 * autoroute.c -- Automatic layout of connections.
 * Copyright (C) 2003 Lars Clausen
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "config.h"

#include "object.h"
#include "connectionpoint.h"
#include "orth_conn.h"

#define MAX_BADNESS 10000.0
/** Add badness if a line is shorter than this distance. */
#define MIN_DIST 1.0
/** The maximum badness that can be given for a line being too short. */
#define MAX_SMALL_BADNESS 10.0

static real length_badness(real len);

static real autoroute_layout_parallel(Point *to,
				      Point **points, guint *num_points);
static real autoroute_layout_orthogonal(Point *to,
					int enddir,
					Point **points, guint *num_points);
static real autoroute_layout_opposite(Point *to,
				      Point **points, guint *num_points);

static guint autolayout_normalize_points(guint startdir, guint enddir,
					 Point start, Point end,
					 Point *newstart, Point *newend);
static Point *autolayout_unnormalize_points(guint dir,
					    Point start,
					    Point *points,
					    guint num_points);

/* Calculate a 'pleasing' route between two connection points.
 * If a good route is found, updates the given OrthConn with the values
 *   and returns TRUE.
 * Otherwise, the OrthConn is untouched, and the function returns FALSE.
 * Handles are not updated by this operation.
 */
gboolean
autoroute_layout_orthconn(OrthConn *conn,
			  ConnectionPoint *from, ConnectionPoint *to)
{
  real min_badness = MAX_BADNESS;
  Point *best_layout;
  guint best_num_points;
  int startdir, enddir;
  
  for (startdir = DIR_NORTH; startdir <= DIR_WEST; startdir *= 2) {
    for (enddir = DIR_NORTH; enddir <= DIR_WEST; enddir *= 2) {
      if ((from->directions & startdir) &&
	  (to->directions & enddir)) {
	real this_badness;
	Point *this_layout;
	guint this_num_points;
	guint normal_enddir;
	Point startpoint, endpoint;
	normal_enddir = autolayout_normalize_points(startdir, enddir,
						    from->pos, to->pos,
						    &startpoint, &endpoint);
	if (normal_enddir == DIR_NORTH ) {
	  this_badness = autoroute_layout_parallel(&endpoint,
						   &this_layout,
						   &this_num_points);
	} else if (normal_enddir == DIR_SOUTH) {
	  this_badness = autoroute_layout_opposite(&endpoint, 
						   &this_layout,
						   &this_num_points);
	} else {
	  this_badness = autoroute_layout_orthogonal(&endpoint,
						     normal_enddir,
						     &this_layout,
						     &this_num_points);
	}
	if (this_badness < min_badness) {
	  min_badness = this_badness;
	  best_layout = autolayout_unnormalize_points(startdir, to->pos,
						      this_layout, 
						      this_num_points);
	  best_num_points = this_num_points;
	} else {
	  g_free(this_layout);
	}
      }
    }    
  }
  
  return min_badness < MAX_BADNESS;
}

/* Returns the badness generated by the given length */
static real
length_badness(real len)
{
  if (len < MIN_DIST) {
    /* This should be zero at MIN_DIST and MAX_SMALL_BADNESS at 0 */
    return 2*MAX_SMALL_BADNESS/(1.0+len/MIN_DIST)-MAX_SMALL_BADNESS;
  } else {
    return len-MIN_DIST;
  }
}

static real
autoroute_layout_parallel(Point *to,
			  Point **points, guint *num_points)
{
  if (fabs(to->x) > MIN_DIST) {
    real top = MIN(-MIN_DIST, to->y-MIN_DIST);
    *points = g_new0(Point, 4);
    /* points[0] is 0,0 */
    points[1]->y = top;
    points[2]->x = to->x;
    points[2]->y = top;
    *points[3] = *to;
    *num_points = 4;
    return length_badness(-top)+
      length_badness(to->x)+
      length_badness(to->y-top);
  }
  return MAX_BADNESS;
}

static real
autoroute_layout_orthogonal(Point *to,
			    int enddir,
			    Point **points, guint *num_points)
{
  return MAX_BADNESS;
}

static real
autoroute_layout_opposite(Point *to,
			  Point **points, guint *num_points)
{
  return MAX_BADNESS;
}

/** Normalizes the directions and points to make startdir be north and
 * the starting point be 0,0.
 * Normalized points are put in newstart and newend.
 * Returns the new enddir.
 */
static guint
autolayout_normalize_points(guint startdir, guint enddir,
			    Point start, Point end,
			    Point *newstart, Point *newend)
{
  newstart->x = 0.0;
  newstart->y = 0.0;
  if (startdir == DIR_NORTH) {
    newend->x = end.x-start.x;
    newend->y = end.y-start.y;
    return enddir;
  }
  /* Insert handling of other stuff here */
  return enddir;
}

/** Reverses the normalizing process of autolayout_normalize_points.
 * Returns the new array of points, freeing the old one if necessary.
 */
static Point *
autolayout_unnormalize_points(guint dir,
			      Point start,
			      Point *points,
			      guint num_points)
{
  Point *newpoints = g_new(Point, num_points);
  int i;
  if (dir == DIR_NORTH) {
    for (i = 0; i < num_points; i++) {
      newpoints[i] = points[i];
      point_add(&newpoints[i], &start);
    }
    g_free(points);
    return newpoints;
  }
  /* Insert handling for other directions here. */
  return NULL;
}
