-- generated by dia/codegen.py

CREATE TABLE tbl_pictures
(
  picture_id       bigserial        PRIMARY KEY NOT NULL                         ,
  title            varchar(64)                           UNIQUE                  ,
  notes            text                                                          
)
;

CREATE TABLE tbl_shapes
(
  shape_id         bigserial        PRIMARY KEY NOT NULL                         ,
  color            varchar(16)                  NOT NULL        DEFAULT 'black'  ,
  origin_x         numeric(6,2)                 NOT NULL                         ,
  origin_y         numeric(6,2)                 NOT NULL                         
)
;
COMMENT ON TABLE tbl_shapes
IS 'Designed for INHERIT by other tables.'
;

CREATE TABLE tbl_circles
(
  radius           numeric(6,2)                 NOT NULL                         
)
INHERITS (tbl_shapes)
;

CREATE TABLE tbl_picture_x_shapes
(
  picture_id       bigint                       NOT NULL                         REFERENCES tbl_pictures (picture_id),
  shape_id         bigint                       NOT NULL                         REFERENCES tbl_shapes (shape_id)
)
;

CREATE TABLE tbl_rectangles
(
  height           numeric(6,2)                 NOT NULL                         ,
  width            numeric(6,2)                 NOT NULL                         
)
INHERITS (tbl_shapes)
;

