TOP = ..\..\..
PRJ_TOP = ..\..
!INCLUDE $(PRJ_TOP)\dia-make.msc

PKG_CFLAGS = -FImsvc_recommended_pragmas.h \
	-I.. -I..\.. \
	$(GTK2_CFLAGS) \
	$(LIBXML2_CFLAGS)  

PKG_LINK = $(INTL_LIBS) $(GLIB_LIBS)

LDFLAGS = /link $(LINKDEBUG) /machine:ix86
INSTALL = copy

CFLAGS = -I. -I$(PRJ_TOP)

## targets
all : \
	gennsh.exe
	
gennsh.exe : gennsh.c gennsh.obj
	$(CC) $(CFLAGS) -Fegennsh.exe gennsh.obj \
	$(LDFLAGS) $(PKG_LINK) /subsystem:console

.c.obj :
	$(CC) $(CFLAGS) -c $(PKG_CFLAGS) $<
